#!/usr/bin/env bash

R='\e[0m'     # reset
r='\e[0;31m'  # red
g='\e[0;32m'  # green
y='\e[0;33m'  # yellow


hesitate() {
    [[ -v NEVER_HESITATE ]] && return 0
    read -p "${1}[Enter] / [s]kip / [Ctrl-C]" ret
    [ "$ret" == "s" ] && return 1
    return 0
}

titlebar() {
    # usage: titlebar color_string_or_var text_to_print, eg:
    #     titlebar $g 'Name of the section' &&
    [[ $# -eq 2 ]] || echo "titlebar takes two args";
    char='█'
    echo -en "${1}"
    for i in $(eval echo {1..$(tput cols)}); do echo -n ${char}; done
    echo -e "\r\t\t ${2} ${R}"
}

fail() { echo -e "[${r}fail${R}] ${@}"; [[ -v DONT_STOP_AFTER_FAIL ]] || exit 2; }

[ -z "$1" ] && fail "provide one arg which will be used as a vhost, user and password"
NAME=$1

destroy() {
    sudo rabbitmqctl clear_permissions -p $NAME $NAME
    sudo rabbitmqctl delete_vhost $NAME
    sudo rabbitmqctl delete_user $NAME
}

add() {
    sudo rabbitmqctl add_user $NAME $NAME
    sudo rabbitmqctl add_vhost $NAME
    sudo rabbitmqctl set_permissions -p $NAME $NAME ".*" ".*" ".*"
    sudo rabbitmqctl set_user_tags $NAME administrator
}

titlebar $y 'This script will destroy all your local rabbitmq server settings and replace them with new ones.'
hesitate && destroy
add
